### ISSUE TITLE
scRNA-seq in GEO are single-end reads

### ISSUE THREAD

**Issue by BenxiaHu** [AmandaKedaigle/BrainOrganoidsReproducibility#4]
thanks.
the deposited scRNA-seq in GEO are single-end reads (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE129519).
would you like to double check them?

**Comment by AmandaKedaigle** [comment]
Ah! That's because we submitted bam files from cellranger to GEO rather than fastqs. Barcode information for each of the reads is in the tags, and you can use 10x's tool to convert back to fastqs if you want: [description here](https://kb.10xgenomics.com/hc/en-us/articles/360006959431-How-to-convert-10x-BAM-files-to-FASTQ-files-while-preserving-the-barcode-information-)

Note that if you do this you will end up with >1 sequencing file per bam file, corresponding to different runs of the same library.
